### ISSUE TITLE
[MiniRebrand] Minirebrand (logo, texts)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-android#1772]
- [x] Launch screen logo
- [ ] Play Store #1774
  - [ ] icon
  - [ ] product name
  - [ ] screenshots
  - [ ] description
  - [ ] what's new
- [x] What's new screen #1773
- [x] Gnosis Safe logo → Safe logo
- [x] "Gnosis" texts → "Safe" or us (company)
- [x] App icon
- [x] App name

URLs, Intercom, and emails stay the same.

**Comment by liliya-soroka** [comment]
verified
App Store changes will be verified after release

app version 3.4.0 -3496rc
