### ISSUE TITLE
[Android] Connectivity mobile and Ledger Nano X

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-android#1889]
As a user 
I want to connect my Ledger Nano X to my Safe
to sign transactions

**Background**
Generally it is possible to connect Ledger Nano X via bluetooth to Android devices. However, there have been incidents/issues. This epic should resolve the issues and, therefore, increase the stability of the connection.

**Tasks/Scope Elements**
Already known tasks are linked below.
An additional task is to investigate if there are other requirements/necessities to implement on Safe side.
If yes, also implement those.
The implementation details are documented in the linked tasks.

- [x] https://github.com/safe-global/safe-android/pull/1860
- [x] https://github.com/safe-global/safe-android/issues/1795#issuecomment-1326625501
- [x] https://github.com/safe-global/safe-android/issues/1890
