### ISSUE TITLE
[Android] [ExecTx] Tracking

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-android#1921]
- [ ] Review screen shown
screen_exec_tx_review

- [ ] Edit transaction fee opened
screen_edit_exec_tx_fee

- [ ] Fee field edited (with parameter = to the name of the field)
user_edit_exec_tx_fee_ fields: 
fields: comma-separated [nonce, gasLimit, maxFee, maxPriorityFee, gasPrice]

- [ ] Advanced parameters opened
screen_exec_tx_review_advanced

- [ ] Select key opened
screen_select_exec_key

- [ ] Select key changed
user_select_exec_key_change

- [ ] Transaction submitted success screen (params: type of key, type of transaction)
screen_exec_tx_submitted
keyType: one of [imported, generated, wallet_connect, ledger_nano_x]
chainId: String

- [ ] Ledger guiding screen(s)
screen_exec_tx_ledger_confirm

- [ ] Transaction submission failed - Log non-fatal? (potentially many errors)
 Let’s not use errors details yet. Can be added later.
user_exec_tx_failed
chainId: Chain id

**Comment by liliya-soroka** [comment]
Returned, because of 2 last events:
1. Tx submitted event doesn't appear if the tx execution is protected with passcode/biometry
2. no parameters information ( I was able to get the even when the passcode was not set up for the tx execution)
![Image](https://github.com/safe-global/safe-android/assets/338622/a714b55b-9e98-4974-8d32-54a5f490c444)
